# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflow.proto\x12\x07zigflow\"\xdc\x03\n\x04\x46low\x12\x18\n\x10time_received_ns\x18\x01 \x01(\x04\x12\x14\n\x0csequence_num\x18\x02 \x01(\r\x12\x15\n\rsampling_rate\x18\x03 \x01(\r\x12\x17\n\x0fsampler_address\x18\x04 \x01(\x0c\x12\x1a\n\x12time_flow_start_ns\x18\x05 \x01(\x04\x12\x18\n\x10time_flow_end_ns\x18\x06 \x01(\x04\x12\r\n\x05\x62ytes\x18\x07 \x01(\x04\x12\x0f\n\x07packets\x18\x08 \x01(\x04\x12\x10\n\x08src_addr\x18\t \x01(\x0c\x12\x10\n\x08\x64st_addr\x18\n \x01(\x0c\x12\r\n\x05\x65type\x18\x0b \x01(\r\x12\r\n\x05proto\x18\x0c \x01(\r\x12\x10\n\x08src_port\x18\r \x01(\r\x12\x10\n\x08\x64st_port\x18\x0e \x01(\r\x12\r\n\x05in_if\x18\x0f \x01(\r\x12\x0e\n\x06out_if\x18\x10 \x01(\r\x12\x11\n\ttcp_flags\x18\x11 \x01(\r\x12\x0e\n\x06src_as\x18\x12 \x01(\r\x12\x0e\n\x06\x64st_as\x18\x13 \x01(\r\x12\x10\n\x08next_hop\x18\x14 \x01(\x0c\x12\x0f\n\x07src_net\x18\x15 \x01(\r\x12\x0f\n\x07\x64st_net\x18\x16 \x01(\r\x12\x1d\n\x15observation_domain_id\x18\x17 \x01(\r\x12\x13\n\x0btemplate_id\x18\x18 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOW._serialized_start=24
  _FLOW._serialized_end=500
# @@protoc_insertion_point(module_scope)
