const std = @import("std");
const Allocator = std.mem.Allocator;

/// Data types for Information Elements (IEs).
pub const DataType = enum {
    unsigned,
    signed,
    float,
    boolean,
    ipv4_address,
    ipv6_address,
    mac_address,
    string,
    octet_array,
    date_time_seconds,
    date_time_milliseconds,
    date_time_microseconds,
    date_time_nanoseconds,
    basic_list,
    sub_template_list,
    sub_template_multi_list,
};

/// Subset of IANA IE IDs used by the parser and formatters.
pub const IeId = enum(u16) {
    octet_delta_count = 1,
    packet_delta_count = 2,
    protocol_identifier = 4,
    tcp_control_bits = 6,
    source_transport_port = 7,
    source_ipv4_address = 8,
    source_ipv4_prefix_length = 9,
    ingress_interface = 10,
    destination_transport_port = 11,
    destination_ipv4_address = 12,
    destination_ipv4_prefix_length = 13,
    egress_interface = 14,
    ip_next_hop_ipv4_address = 15,
    bgp_source_as_number = 16,
    bgp_destination_as_number = 17,
    source_ipv6_address = 27,
    destination_ipv6_address = 28,
    source_ipv6_prefix_length = 29,
    destination_ipv6_prefix_length = 30,
    sampling_interval = 34,
    sampler_random_interval = 50,
    ip_next_hop_ipv6_address = 62,
    flow_start_seconds = 150,
    flow_end_seconds = 151,
    flow_start_milliseconds = 152,
    flow_end_milliseconds = 153,
    flow_start_microseconds = 154,
    flow_end_microseconds = 155,
    flow_start_nanoseconds = 156,
    flow_end_nanoseconds = 157,
    ethernet_type = 256,
    sampling_packet_interval = 305,
    _,
};

/// Information Element (IE) metadata.
pub const FieldInfo = struct {
    id: u16,
    pen: ?u32,
    name: []const u8,
    data_type: DataType,
};

/// IANA-assigned Information Elements (IEs): https://www.iana.org/assignments/ipfix/ipfix.xhtml
const iana = [_]FieldInfo{
    .{ .id = 1, .pen = null, .name = "octetDeltaCount", .data_type = .unsigned },
    .{ .id = 2, .pen = null, .name = "packetDeltaCount", .data_type = .unsigned },
    .{ .id = 3, .pen = null, .name = "deltaFlowCount", .data_type = .unsigned },
    .{ .id = 4, .pen = null, .name = "protocolIdentifier", .data_type = .unsigned },
    .{ .id = 5, .pen = null, .name = "ipClassOfService", .data_type = .unsigned },
    .{ .id = 6, .pen = null, .name = "tcpControlBits", .data_type = .unsigned },
    .{ .id = 7, .pen = null, .name = "sourceTransportPort", .data_type = .unsigned },
    .{ .id = 8, .pen = null, .name = "sourceIPv4Address", .data_type = .ipv4_address },
    .{ .id = 9, .pen = null, .name = "sourceIPv4PrefixLength", .data_type = .unsigned },
    .{ .id = 10, .pen = null, .name = "ingressInterface", .data_type = .unsigned },
    .{ .id = 11, .pen = null, .name = "destinationTransportPort", .data_type = .unsigned },
    .{ .id = 12, .pen = null, .name = "destinationIPv4Address", .data_type = .ipv4_address },
    .{ .id = 13, .pen = null, .name = "destinationIPv4PrefixLength", .data_type = .unsigned },
    .{ .id = 14, .pen = null, .name = "egressInterface", .data_type = .unsigned },
    .{ .id = 15, .pen = null, .name = "ipNextHopIPv4Address", .data_type = .ipv4_address },
    .{ .id = 16, .pen = null, .name = "bgpSourceAsNumber", .data_type = .unsigned },
    .{ .id = 17, .pen = null, .name = "bgpDestinationAsNumber", .data_type = .unsigned },
    .{ .id = 18, .pen = null, .name = "bgpNextHopIPv4Address", .data_type = .ipv4_address },
    .{ .id = 19, .pen = null, .name = "postMCastPacketDeltaCount", .data_type = .unsigned },
    .{ .id = 20, .pen = null, .name = "postMCastOctetDeltaCount", .data_type = .unsigned },
    .{ .id = 21, .pen = null, .name = "flowEndSysUpTime", .data_type = .unsigned },
    .{ .id = 22, .pen = null, .name = "flowStartSysUpTime", .data_type = .unsigned },
    .{ .id = 23, .pen = null, .name = "postOctetDeltaCount", .data_type = .unsigned },
    .{ .id = 24, .pen = null, .name = "postPacketDeltaCount", .data_type = .unsigned },
    .{ .id = 25, .pen = null, .name = "minimumIpTotalLength", .data_type = .unsigned },
    .{ .id = 26, .pen = null, .name = "maximumIpTotalLength", .data_type = .unsigned },
    .{ .id = 27, .pen = null, .name = "sourceIPv6Address", .data_type = .ipv6_address },
    .{ .id = 28, .pen = null, .name = "destinationIPv6Address", .data_type = .ipv6_address },
    .{ .id = 29, .pen = null, .name = "sourceIPv6PrefixLength", .data_type = .unsigned },
    .{ .id = 30, .pen = null, .name = "destinationIPv6PrefixLength", .data_type = .unsigned },
    .{ .id = 31, .pen = null, .name = "flowLabelIPv6", .data_type = .unsigned },
    .{ .id = 32, .pen = null, .name = "icmpTypeCodeIPv4", .data_type = .unsigned },
    .{ .id = 33, .pen = null, .name = "igmpType", .data_type = .unsigned },
    .{ .id = 34, .pen = null, .name = "samplingInterval", .data_type = .unsigned },
    .{ .id = 35, .pen = null, .name = "samplingAlgorithm", .data_type = .unsigned },
    .{ .id = 36, .pen = null, .name = "flowActiveTimeout", .data_type = .unsigned },
    .{ .id = 37, .pen = null, .name = "flowIdleTimeout", .data_type = .unsigned },
    .{ .id = 38, .pen = null, .name = "engineType", .data_type = .unsigned },
    .{ .id = 39, .pen = null, .name = "engineId", .data_type = .unsigned },
    .{ .id = 40, .pen = null, .name = "exportedOctetTotalCount", .data_type = .unsigned },
    .{ .id = 41, .pen = null, .name = "exportedMessageTotalCount", .data_type = .unsigned },
    .{ .id = 42, .pen = null, .name = "exportedFlowRecordTotalCount", .data_type = .unsigned },
    .{ .id = 43, .pen = null, .name = "ipv4RouterSc", .data_type = .ipv4_address },
    .{ .id = 44, .pen = null, .name = "sourceIPv4Prefix", .data_type = .ipv4_address },
    .{ .id = 45, .pen = null, .name = "destinationIPv4Prefix", .data_type = .ipv4_address },
    .{ .id = 46, .pen = null, .name = "mplsTopLabelType", .data_type = .unsigned },
    .{ .id = 47, .pen = null, .name = "mplsTopLabelIPv4Address", .data_type = .ipv4_address },
    .{ .id = 48, .pen = null, .name = "samplerId", .data_type = .unsigned },
    .{ .id = 49, .pen = null, .name = "samplerMode", .data_type = .unsigned },
    .{ .id = 50, .pen = null, .name = "samplerRandomInterval", .data_type = .unsigned },
    .{ .id = 51, .pen = null, .name = "classId", .data_type = .unsigned },
    .{ .id = 52, .pen = null, .name = "minimumTTL", .data_type = .unsigned },
    .{ .id = 53, .pen = null, .name = "maximumTTL", .data_type = .unsigned },
    .{ .id = 54, .pen = null, .name = "fragmentIdentification", .data_type = .unsigned },
    .{ .id = 55, .pen = null, .name = "postIpClassOfService", .data_type = .unsigned },
    .{ .id = 56, .pen = null, .name = "sourceMacAddress", .data_type = .mac_address },
    .{ .id = 57, .pen = null, .name = "postDestinationMacAddress", .data_type = .mac_address },
    .{ .id = 58, .pen = null, .name = "vlanId", .data_type = .unsigned },
    .{ .id = 59, .pen = null, .name = "postVlanId", .data_type = .unsigned },
    .{ .id = 60, .pen = null, .name = "ipVersion", .data_type = .unsigned },
    .{ .id = 61, .pen = null, .name = "flowDirection", .data_type = .unsigned },
    .{ .id = 62, .pen = null, .name = "ipNextHopIPv6Address", .data_type = .ipv6_address },
    .{ .id = 63, .pen = null, .name = "bgpNextHopIPv6Address", .data_type = .ipv6_address },
    .{ .id = 64, .pen = null, .name = "ipv6ExtensionHeaders", .data_type = .unsigned },
    .{ .id = 70, .pen = null, .name = "mplsTopLabelStackSection", .data_type = .octet_array },
    .{ .id = 71, .pen = null, .name = "mplsLabelStackSection2", .data_type = .octet_array },
    .{ .id = 72, .pen = null, .name = "mplsLabelStackSection3", .data_type = .octet_array },
    .{ .id = 73, .pen = null, .name = "mplsLabelStackSection4", .data_type = .octet_array },
    .{ .id = 74, .pen = null, .name = "mplsLabelStackSection5", .data_type = .octet_array },
    .{ .id = 75, .pen = null, .name = "mplsLabelStackSection6", .data_type = .octet_array },
    .{ .id = 76, .pen = null, .name = "mplsLabelStackSection7", .data_type = .octet_array },
    .{ .id = 77, .pen = null, .name = "mplsLabelStackSection8", .data_type = .octet_array },
    .{ .id = 78, .pen = null, .name = "mplsLabelStackSection9", .data_type = .octet_array },
    .{ .id = 79, .pen = null, .name = "mplsLabelStackSection10", .data_type = .octet_array },
    .{ .id = 80, .pen = null, .name = "destinationMacAddress", .data_type = .mac_address },
    .{ .id = 81, .pen = null, .name = "postSourceMacAddress", .data_type = .mac_address },
    .{ .id = 82, .pen = null, .name = "interfaceName", .data_type = .string },
    .{ .id = 83, .pen = null, .name = "interfaceDescription", .data_type = .string },
    .{ .id = 84, .pen = null, .name = "samplerName", .data_type = .string },
    .{ .id = 85, .pen = null, .name = "octetTotalCount", .data_type = .unsigned },
    .{ .id = 86, .pen = null, .name = "packetTotalCount", .data_type = .unsigned },
    .{ .id = 87, .pen = null, .name = "flagsAndSamplerId", .data_type = .unsigned },
    .{ .id = 88, .pen = null, .name = "fragmentOffset", .data_type = .unsigned },
    .{ .id = 89, .pen = null, .name = "forwardingStatus", .data_type = .unsigned },
    .{ .id = 90, .pen = null, .name = "mplsVpnRouteDistinguisher", .data_type = .octet_array },
    .{ .id = 91, .pen = null, .name = "mplsTopLabelPrefixLength", .data_type = .unsigned },
    .{ .id = 92, .pen = null, .name = "srcTrafficIndex", .data_type = .unsigned },
    .{ .id = 93, .pen = null, .name = "dstTrafficIndex", .data_type = .unsigned },
    .{ .id = 94, .pen = null, .name = "applicationDescription", .data_type = .string },
    .{ .id = 95, .pen = null, .name = "applicationId", .data_type = .octet_array },
    .{ .id = 96, .pen = null, .name = "applicationName", .data_type = .string },
    .{ .id = 98, .pen = null, .name = "postIpDiffServCodePoint", .data_type = .unsigned },
    .{ .id = 99, .pen = null, .name = "multicastReplicationFactor", .data_type = .unsigned },
    .{ .id = 100, .pen = null, .name = "className", .data_type = .string },
    .{ .id = 101, .pen = null, .name = "classificationEngineId", .data_type = .unsigned },
    .{ .id = 102, .pen = null, .name = "layer2packetSectionOffset", .data_type = .unsigned },
    .{ .id = 103, .pen = null, .name = "layer2packetSectionSize", .data_type = .unsigned },
    .{ .id = 104, .pen = null, .name = "layer2packetSectionData", .data_type = .octet_array },
    .{ .id = 128, .pen = null, .name = "bgpNextAdjacentAsNumber", .data_type = .unsigned },
    .{ .id = 129, .pen = null, .name = "bgpPrevAdjacentAsNumber", .data_type = .unsigned },
    .{ .id = 130, .pen = null, .name = "exporterIPv4Address", .data_type = .ipv4_address },
    .{ .id = 131, .pen = null, .name = "exporterIPv6Address", .data_type = .ipv6_address },
    .{ .id = 132, .pen = null, .name = "droppedOctetDeltaCount", .data_type = .unsigned },
    .{ .id = 133, .pen = null, .name = "droppedPacketDeltaCount", .data_type = .unsigned },
    .{ .id = 134, .pen = null, .name = "droppedOctetTotalCount", .data_type = .unsigned },
    .{ .id = 135, .pen = null, .name = "droppedPacketTotalCount", .data_type = .unsigned },
    .{ .id = 136, .pen = null, .name = "flowEndReason", .data_type = .unsigned },
    .{ .id = 137, .pen = null, .name = "commonPropertiesId", .data_type = .unsigned },
    .{ .id = 138, .pen = null, .name = "observationPointId", .data_type = .unsigned },
    .{ .id = 139, .pen = null, .name = "icmpTypeCodeIPv6", .data_type = .unsigned },
    .{ .id = 140, .pen = null, .name = "mplsTopLabelIPv6Address", .data_type = .ipv6_address },
    .{ .id = 141, .pen = null, .name = "lineCardId", .data_type = .unsigned },
    .{ .id = 142, .pen = null, .name = "portId", .data_type = .unsigned },
    .{ .id = 143, .pen = null, .name = "meteringProcessId", .data_type = .unsigned },
    .{ .id = 144, .pen = null, .name = "exportingProcessId", .data_type = .unsigned },
    .{ .id = 145, .pen = null, .name = "templateId", .data_type = .unsigned },
    .{ .id = 146, .pen = null, .name = "wlanChannelId", .data_type = .unsigned },
    .{ .id = 147, .pen = null, .name = "wlanSSID", .data_type = .string },
    .{ .id = 148, .pen = null, .name = "flowId", .data_type = .unsigned },
    .{ .id = 149, .pen = null, .name = "observationDomainId", .data_type = .unsigned },
    .{ .id = 150, .pen = null, .name = "flowStartSeconds", .data_type = .date_time_seconds },
    .{ .id = 151, .pen = null, .name = "flowEndSeconds", .data_type = .date_time_seconds },
    .{ .id = 152, .pen = null, .name = "flowStartMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 153, .pen = null, .name = "flowEndMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 154, .pen = null, .name = "flowStartMicroseconds", .data_type = .date_time_microseconds },
    .{ .id = 155, .pen = null, .name = "flowEndMicroseconds", .data_type = .date_time_microseconds },
    .{ .id = 156, .pen = null, .name = "flowStartNanoseconds", .data_type = .date_time_nanoseconds },
    .{ .id = 157, .pen = null, .name = "flowEndNanoseconds", .data_type = .date_time_nanoseconds },
    .{ .id = 158, .pen = null, .name = "flowStartDeltaMicroseconds", .data_type = .unsigned },
    .{ .id = 159, .pen = null, .name = "flowEndDeltaMicroseconds", .data_type = .unsigned },
    .{ .id = 160, .pen = null, .name = "systemInitTimeMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 161, .pen = null, .name = "flowDurationMilliseconds", .data_type = .unsigned },
    .{ .id = 162, .pen = null, .name = "flowDurationMicroseconds", .data_type = .unsigned },
    .{ .id = 163, .pen = null, .name = "observedFlowTotalCount", .data_type = .unsigned },
    .{ .id = 164, .pen = null, .name = "ignoredPacketTotalCount", .data_type = .unsigned },
    .{ .id = 165, .pen = null, .name = "ignoredOctetTotalCount", .data_type = .unsigned },
    .{ .id = 166, .pen = null, .name = "notSentFlowTotalCount", .data_type = .unsigned },
    .{ .id = 167, .pen = null, .name = "notSentPacketTotalCount", .data_type = .unsigned },
    .{ .id = 168, .pen = null, .name = "notSentOctetTotalCount", .data_type = .unsigned },
    .{ .id = 169, .pen = null, .name = "destinationIPv6Prefix", .data_type = .ipv6_address },
    .{ .id = 170, .pen = null, .name = "sourceIPv6Prefix", .data_type = .ipv6_address },
    .{ .id = 171, .pen = null, .name = "postOctetTotalCount", .data_type = .unsigned },
    .{ .id = 172, .pen = null, .name = "postPacketTotalCount", .data_type = .unsigned },
    .{ .id = 173, .pen = null, .name = "flowKeyIndicator", .data_type = .unsigned },
    .{ .id = 174, .pen = null, .name = "postMCastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 175, .pen = null, .name = "postMCastOctetTotalCount", .data_type = .unsigned },
    .{ .id = 176, .pen = null, .name = "icmpTypeIPv4", .data_type = .unsigned },
    .{ .id = 177, .pen = null, .name = "icmpCodeIPv4", .data_type = .unsigned },
    .{ .id = 178, .pen = null, .name = "icmpTypeIPv6", .data_type = .unsigned },
    .{ .id = 179, .pen = null, .name = "icmpCodeIPv6", .data_type = .unsigned },
    .{ .id = 180, .pen = null, .name = "udpSourcePort", .data_type = .unsigned },
    .{ .id = 181, .pen = null, .name = "udpDestinationPort", .data_type = .unsigned },
    .{ .id = 182, .pen = null, .name = "tcpSourcePort", .data_type = .unsigned },
    .{ .id = 183, .pen = null, .name = "tcpDestinationPort", .data_type = .unsigned },
    .{ .id = 184, .pen = null, .name = "tcpSequenceNumber", .data_type = .unsigned },
    .{ .id = 185, .pen = null, .name = "tcpAcknowledgementNumber", .data_type = .unsigned },
    .{ .id = 186, .pen = null, .name = "tcpWindowSize", .data_type = .unsigned },
    .{ .id = 187, .pen = null, .name = "tcpUrgentPointer", .data_type = .unsigned },
    .{ .id = 188, .pen = null, .name = "tcpHeaderLength", .data_type = .unsigned },
    .{ .id = 189, .pen = null, .name = "ipHeaderLength", .data_type = .unsigned },
    .{ .id = 190, .pen = null, .name = "totalLengthIPv4", .data_type = .unsigned },
    .{ .id = 191, .pen = null, .name = "payloadLengthIPv6", .data_type = .unsigned },
    .{ .id = 192, .pen = null, .name = "ipTTL", .data_type = .unsigned },
    .{ .id = 193, .pen = null, .name = "nextHeaderIPv6", .data_type = .unsigned },
    .{ .id = 194, .pen = null, .name = "mplsPayloadLength", .data_type = .unsigned },
    .{ .id = 195, .pen = null, .name = "ipDiffServCodePoint", .data_type = .unsigned },
    .{ .id = 196, .pen = null, .name = "ipPrecedence", .data_type = .unsigned },
    .{ .id = 197, .pen = null, .name = "fragmentFlags", .data_type = .unsigned },
    .{ .id = 198, .pen = null, .name = "octetDeltaSumOfSquares", .data_type = .unsigned },
    .{ .id = 199, .pen = null, .name = "octetTotalSumOfSquares", .data_type = .unsigned },
    .{ .id = 200, .pen = null, .name = "mplsTopLabelTTL", .data_type = .unsigned },
    .{ .id = 201, .pen = null, .name = "mplsLabelStackLength", .data_type = .unsigned },
    .{ .id = 202, .pen = null, .name = "mplsLabelStackDepth", .data_type = .unsigned },
    .{ .id = 203, .pen = null, .name = "mplsTopLabelExp", .data_type = .unsigned },
    .{ .id = 204, .pen = null, .name = "ipPayloadLength", .data_type = .unsigned },
    .{ .id = 205, .pen = null, .name = "udpMessageLength", .data_type = .unsigned },
    .{ .id = 206, .pen = null, .name = "isMulticast", .data_type = .unsigned },
    .{ .id = 207, .pen = null, .name = "ipv4IHL", .data_type = .unsigned },
    .{ .id = 208, .pen = null, .name = "ipv4Options", .data_type = .unsigned },
    .{ .id = 209, .pen = null, .name = "tcpOptions", .data_type = .unsigned },
    .{ .id = 210, .pen = null, .name = "paddingOctets", .data_type = .octet_array },
    .{ .id = 211, .pen = null, .name = "collectorIPv4Address", .data_type = .ipv4_address },
    .{ .id = 212, .pen = null, .name = "collectorIPv6Address", .data_type = .ipv6_address },
    .{ .id = 213, .pen = null, .name = "exportInterface", .data_type = .unsigned },
    .{ .id = 214, .pen = null, .name = "exportProtocolVersion", .data_type = .unsigned },
    .{ .id = 215, .pen = null, .name = "exportTransportProtocol", .data_type = .unsigned },
    .{ .id = 216, .pen = null, .name = "collectorTransportPort", .data_type = .unsigned },
    .{ .id = 217, .pen = null, .name = "exporterTransportPort", .data_type = .unsigned },
    .{ .id = 218, .pen = null, .name = "tcpSynTotalCount", .data_type = .unsigned },
    .{ .id = 219, .pen = null, .name = "tcpFinTotalCount", .data_type = .unsigned },
    .{ .id = 220, .pen = null, .name = "tcpRstTotalCount", .data_type = .unsigned },
    .{ .id = 221, .pen = null, .name = "tcpPshTotalCount", .data_type = .unsigned },
    .{ .id = 222, .pen = null, .name = "tcpAckTotalCount", .data_type = .unsigned },
    .{ .id = 223, .pen = null, .name = "tcpUrgTotalCount", .data_type = .unsigned },
    .{ .id = 224, .pen = null, .name = "ipTotalLength", .data_type = .unsigned },
    .{ .id = 225, .pen = null, .name = "postNATSourceIPv4Address", .data_type = .ipv4_address },
    .{ .id = 226, .pen = null, .name = "postNATDestinationIPv4Address", .data_type = .ipv4_address },
    .{ .id = 227, .pen = null, .name = "postNAPTSourceTransportPort", .data_type = .unsigned },
    .{ .id = 228, .pen = null, .name = "postNAPTDestinationTransportPort", .data_type = .unsigned },
    .{ .id = 229, .pen = null, .name = "natOriginatingAddressRealm", .data_type = .unsigned },
    .{ .id = 230, .pen = null, .name = "natEvent", .data_type = .unsigned },
    .{ .id = 231, .pen = null, .name = "initiatorOctets", .data_type = .unsigned },
    .{ .id = 232, .pen = null, .name = "responderOctets", .data_type = .unsigned },
    .{ .id = 233, .pen = null, .name = "firewallEvent", .data_type = .unsigned },
    .{ .id = 234, .pen = null, .name = "ingressVRFID", .data_type = .unsigned },
    .{ .id = 235, .pen = null, .name = "egressVRFID", .data_type = .unsigned },
    .{ .id = 236, .pen = null, .name = "VRFname", .data_type = .string },
    .{ .id = 237, .pen = null, .name = "postMplsTopLabelExp", .data_type = .unsigned },
    .{ .id = 238, .pen = null, .name = "tcpWindowScale", .data_type = .unsigned },
    .{ .id = 239, .pen = null, .name = "biflowDirection", .data_type = .unsigned },
    .{ .id = 240, .pen = null, .name = "ethernetHeaderLength", .data_type = .unsigned },
    .{ .id = 241, .pen = null, .name = "ethernetPayloadLength", .data_type = .unsigned },
    .{ .id = 242, .pen = null, .name = "ethernetTotalLength", .data_type = .unsigned },
    .{ .id = 243, .pen = null, .name = "dot1qVlanId", .data_type = .unsigned },
    .{ .id = 244, .pen = null, .name = "dot1qPriority", .data_type = .unsigned },
    .{ .id = 245, .pen = null, .name = "dot1qCustomerVlanId", .data_type = .unsigned },
    .{ .id = 246, .pen = null, .name = "dot1qCustomerPriority", .data_type = .unsigned },
    .{ .id = 247, .pen = null, .name = "metroEvcId", .data_type = .string },
    .{ .id = 248, .pen = null, .name = "metroEvcType", .data_type = .unsigned },
    .{ .id = 249, .pen = null, .name = "pseudoWireId", .data_type = .unsigned },
    .{ .id = 250, .pen = null, .name = "pseudoWireType", .data_type = .unsigned },
    .{ .id = 251, .pen = null, .name = "pseudoWireControlWord", .data_type = .unsigned },
    .{ .id = 252, .pen = null, .name = "ingressPhysicalInterface", .data_type = .unsigned },
    .{ .id = 253, .pen = null, .name = "egressPhysicalInterface", .data_type = .unsigned },
    .{ .id = 254, .pen = null, .name = "postDot1qVlanId", .data_type = .unsigned },
    .{ .id = 255, .pen = null, .name = "postDot1qCustomerVlanId", .data_type = .unsigned },
    .{ .id = 256, .pen = null, .name = "ethernetType", .data_type = .unsigned },
    .{ .id = 257, .pen = null, .name = "postIpPrecedence", .data_type = .unsigned },
    .{ .id = 258, .pen = null, .name = "collectionTimeMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 259, .pen = null, .name = "exportSctpStreamId", .data_type = .unsigned },
    .{ .id = 260, .pen = null, .name = "maxExportSeconds", .data_type = .date_time_seconds },
    .{ .id = 261, .pen = null, .name = "maxFlowEndSeconds", .data_type = .date_time_seconds },
    .{ .id = 262, .pen = null, .name = "messageMD5Checksum", .data_type = .octet_array },
    .{ .id = 263, .pen = null, .name = "messageScope", .data_type = .unsigned },
    .{ .id = 264, .pen = null, .name = "minExportSeconds", .data_type = .date_time_seconds },
    .{ .id = 265, .pen = null, .name = "minFlowStartSeconds", .data_type = .date_time_seconds },
    .{ .id = 266, .pen = null, .name = "opaqueOctets", .data_type = .octet_array },
    .{ .id = 267, .pen = null, .name = "sessionScope", .data_type = .unsigned },
    .{ .id = 268, .pen = null, .name = "maxFlowEndMicroseconds", .data_type = .date_time_microseconds },
    .{ .id = 269, .pen = null, .name = "maxFlowEndMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 270, .pen = null, .name = "maxFlowEndNanoseconds", .data_type = .date_time_nanoseconds },
    .{ .id = 271, .pen = null, .name = "minFlowStartMicroseconds", .data_type = .date_time_microseconds },
    .{ .id = 272, .pen = null, .name = "minFlowStartMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 273, .pen = null, .name = "minFlowStartNanoseconds", .data_type = .date_time_nanoseconds },
    .{ .id = 274, .pen = null, .name = "collectorCertificate", .data_type = .octet_array },
    .{ .id = 275, .pen = null, .name = "exporterCertificate", .data_type = .octet_array },
    .{ .id = 276, .pen = null, .name = "dataRecordsReliability", .data_type = .boolean },
    .{ .id = 277, .pen = null, .name = "observationPointType", .data_type = .unsigned },
    .{ .id = 278, .pen = null, .name = "newConnectionDeltaCount", .data_type = .unsigned },
    .{ .id = 279, .pen = null, .name = "connectionSumDurationSeconds", .data_type = .unsigned },
    .{ .id = 280, .pen = null, .name = "connectionTransactionId", .data_type = .unsigned },
    .{ .id = 281, .pen = null, .name = "postNATSourceIPv6Address", .data_type = .ipv6_address },
    .{ .id = 282, .pen = null, .name = "postNATDestinationIPv6Address", .data_type = .ipv6_address },
    .{ .id = 283, .pen = null, .name = "natPoolId", .data_type = .unsigned },
    .{ .id = 284, .pen = null, .name = "natPoolName", .data_type = .string },
    .{ .id = 285, .pen = null, .name = "anonymizationFlags", .data_type = .unsigned },
    .{ .id = 286, .pen = null, .name = "anonymizationTechnique", .data_type = .unsigned },
    .{ .id = 287, .pen = null, .name = "informationElementIndex", .data_type = .unsigned },
    .{ .id = 288, .pen = null, .name = "p2pTechnology", .data_type = .string },
    .{ .id = 289, .pen = null, .name = "tunnelTechnology", .data_type = .string },
    .{ .id = 290, .pen = null, .name = "encryptedTechnology", .data_type = .string },
    .{ .id = 291, .pen = null, .name = "basicList", .data_type = .basic_list },
    .{ .id = 292, .pen = null, .name = "subTemplateList", .data_type = .sub_template_list },
    .{ .id = 293, .pen = null, .name = "subTemplateMultiList", .data_type = .sub_template_multi_list },
    .{ .id = 294, .pen = null, .name = "bgpValidityState", .data_type = .unsigned },
    .{ .id = 295, .pen = null, .name = "IPSecSPI", .data_type = .unsigned },
    .{ .id = 296, .pen = null, .name = "greKey", .data_type = .unsigned },
    .{ .id = 297, .pen = null, .name = "natType", .data_type = .unsigned },
    .{ .id = 298, .pen = null, .name = "initiatorPackets", .data_type = .unsigned },
    .{ .id = 299, .pen = null, .name = "responderPackets", .data_type = .unsigned },
    .{ .id = 300, .pen = null, .name = "observationDomainName", .data_type = .string },
    .{ .id = 301, .pen = null, .name = "selectionSequenceId", .data_type = .unsigned },
    .{ .id = 302, .pen = null, .name = "selectorId", .data_type = .unsigned },
    .{ .id = 303, .pen = null, .name = "informationElementId", .data_type = .unsigned },
    .{ .id = 304, .pen = null, .name = "selectorAlgorithm", .data_type = .unsigned },
    .{ .id = 305, .pen = null, .name = "samplingPacketInterval", .data_type = .unsigned },
    .{ .id = 306, .pen = null, .name = "samplingPacketSpace", .data_type = .unsigned },
    .{ .id = 307, .pen = null, .name = "samplingTimeInterval", .data_type = .unsigned },
    .{ .id = 308, .pen = null, .name = "samplingTimeSpace", .data_type = .unsigned },
    .{ .id = 309, .pen = null, .name = "samplingSize", .data_type = .unsigned },
    .{ .id = 310, .pen = null, .name = "samplingPopulation", .data_type = .unsigned },
    .{ .id = 311, .pen = null, .name = "samplingProbability", .data_type = .float },
    .{ .id = 312, .pen = null, .name = "dataLinkFrameSize", .data_type = .unsigned },
    .{ .id = 313, .pen = null, .name = "ipHeaderPacketSection", .data_type = .octet_array },
    .{ .id = 314, .pen = null, .name = "ipPayloadPacketSection", .data_type = .octet_array },
    .{ .id = 315, .pen = null, .name = "dataLinkFrameSection", .data_type = .octet_array },
    .{ .id = 316, .pen = null, .name = "mplsLabelStackSection", .data_type = .octet_array },
    .{ .id = 317, .pen = null, .name = "mplsPayloadPacketSection", .data_type = .octet_array },
    .{ .id = 318, .pen = null, .name = "selectorIdTotalPktsObserved", .data_type = .unsigned },
    .{ .id = 319, .pen = null, .name = "selectorIdTotalPktsSelected", .data_type = .unsigned },
    .{ .id = 320, .pen = null, .name = "absoluteError", .data_type = .float },
    .{ .id = 321, .pen = null, .name = "relativeError", .data_type = .float },
    .{ .id = 322, .pen = null, .name = "observationTimeSeconds", .data_type = .date_time_seconds },
    .{ .id = 323, .pen = null, .name = "observationTimeMilliseconds", .data_type = .date_time_milliseconds },
    .{ .id = 324, .pen = null, .name = "observationTimeMicroseconds", .data_type = .date_time_microseconds },
    .{ .id = 325, .pen = null, .name = "observationTimeNanoseconds", .data_type = .date_time_nanoseconds },
    .{ .id = 326, .pen = null, .name = "digestHashValue", .data_type = .unsigned },
    .{ .id = 327, .pen = null, .name = "hashIPPayloadOffset", .data_type = .unsigned },
    .{ .id = 328, .pen = null, .name = "hashIPPayloadSize", .data_type = .unsigned },
    .{ .id = 329, .pen = null, .name = "hashOutputRangeMin", .data_type = .unsigned },
    .{ .id = 330, .pen = null, .name = "hashOutputRangeMax", .data_type = .unsigned },
    .{ .id = 331, .pen = null, .name = "hashSelectedRangeMin", .data_type = .unsigned },
    .{ .id = 332, .pen = null, .name = "hashSelectedRangeMax", .data_type = .unsigned },
    .{ .id = 333, .pen = null, .name = "hashDigestOutput", .data_type = .boolean },
    .{ .id = 334, .pen = null, .name = "hashInitialiserValue", .data_type = .unsigned },
    .{ .id = 335, .pen = null, .name = "selectorName", .data_type = .string },
    .{ .id = 336, .pen = null, .name = "upperCILimit", .data_type = .float },
    .{ .id = 337, .pen = null, .name = "lowerCILimit", .data_type = .float },
    .{ .id = 338, .pen = null, .name = "confidenceLevel", .data_type = .float },
    .{ .id = 339, .pen = null, .name = "informationElementDataType", .data_type = .unsigned },
    .{ .id = 340, .pen = null, .name = "informationElementDescription", .data_type = .string },
    .{ .id = 341, .pen = null, .name = "informationElementName", .data_type = .string },
    .{ .id = 342, .pen = null, .name = "informationElementRangeBegin", .data_type = .unsigned },
    .{ .id = 343, .pen = null, .name = "informationElementRangeEnd", .data_type = .unsigned },
    .{ .id = 344, .pen = null, .name = "informationElementSemantics", .data_type = .unsigned },
    .{ .id = 345, .pen = null, .name = "informationElementUnits", .data_type = .unsigned },
    .{ .id = 346, .pen = null, .name = "privateEnterpriseNumber", .data_type = .unsigned },
    .{ .id = 347, .pen = null, .name = "virtualStationInterfaceId", .data_type = .octet_array },
    .{ .id = 348, .pen = null, .name = "virtualStationInterfaceName", .data_type = .string },
    .{ .id = 349, .pen = null, .name = "virtualStationUUID", .data_type = .octet_array },
    .{ .id = 350, .pen = null, .name = "virtualStationName", .data_type = .string },
    .{ .id = 351, .pen = null, .name = "layer2SegmentId", .data_type = .unsigned },
    .{ .id = 352, .pen = null, .name = "layer2OctetDeltaCount", .data_type = .unsigned },
    .{ .id = 353, .pen = null, .name = "layer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 354, .pen = null, .name = "ingressUnicastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 355, .pen = null, .name = "ingressMulticastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 356, .pen = null, .name = "ingressBroadcastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 357, .pen = null, .name = "egressUnicastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 358, .pen = null, .name = "egressBroadcastPacketTotalCount", .data_type = .unsigned },
    .{ .id = 359, .pen = null, .name = "monitoringIntervalStartMilliSeconds", .data_type = .date_time_milliseconds },
    .{ .id = 360, .pen = null, .name = "monitoringIntervalEndMilliSeconds", .data_type = .date_time_milliseconds },
    .{ .id = 361, .pen = null, .name = "portRangeStart", .data_type = .unsigned },
    .{ .id = 362, .pen = null, .name = "portRangeEnd", .data_type = .unsigned },
    .{ .id = 363, .pen = null, .name = "portRangeStepSize", .data_type = .unsigned },
    .{ .id = 364, .pen = null, .name = "portRangeNumPorts", .data_type = .unsigned },
    .{ .id = 365, .pen = null, .name = "staMacAddress", .data_type = .mac_address },
    .{ .id = 366, .pen = null, .name = "staIPv4Address", .data_type = .ipv4_address },
    .{ .id = 367, .pen = null, .name = "wtpMacAddress", .data_type = .mac_address },
    .{ .id = 368, .pen = null, .name = "ingressInterfaceType", .data_type = .unsigned },
    .{ .id = 369, .pen = null, .name = "egressInterfaceType", .data_type = .unsigned },
    .{ .id = 370, .pen = null, .name = "rtpSequenceNumber", .data_type = .unsigned },
    .{ .id = 371, .pen = null, .name = "userName", .data_type = .string },
    .{ .id = 372, .pen = null, .name = "applicationCategoryName", .data_type = .string },
    .{ .id = 373, .pen = null, .name = "applicationSubCategoryName", .data_type = .string },
    .{ .id = 374, .pen = null, .name = "applicationGroupName", .data_type = .string },
    .{ .id = 375, .pen = null, .name = "originalFlowsPresent", .data_type = .unsigned },
    .{ .id = 376, .pen = null, .name = "originalFlowsInitiated", .data_type = .unsigned },
    .{ .id = 377, .pen = null, .name = "originalFlowsCompleted", .data_type = .unsigned },
    .{ .id = 378, .pen = null, .name = "distinctCountOfSourceIPAddress", .data_type = .unsigned },
    .{ .id = 379, .pen = null, .name = "distinctCountOfDestinationIPAddress", .data_type = .unsigned },
    .{ .id = 380, .pen = null, .name = "distinctCountOfSourceIPv4Address", .data_type = .unsigned },
    .{ .id = 381, .pen = null, .name = "distinctCountOfDestinationIPv4Address", .data_type = .unsigned },
    .{ .id = 382, .pen = null, .name = "distinctCountOfSourceIPv6Address", .data_type = .unsigned },
    .{ .id = 383, .pen = null, .name = "distinctCountOfDestinationIPv6Address", .data_type = .unsigned },
    .{ .id = 384, .pen = null, .name = "valueDistributionMethod", .data_type = .unsigned },
    .{ .id = 385, .pen = null, .name = "rfc3550JitterMilliseconds", .data_type = .unsigned },
    .{ .id = 386, .pen = null, .name = "rfc3550JitterMicroseconds", .data_type = .unsigned },
    .{ .id = 387, .pen = null, .name = "rfc3550JitterNanoseconds", .data_type = .unsigned },
    .{ .id = 388, .pen = null, .name = "dot1qDEI", .data_type = .boolean },
    .{ .id = 389, .pen = null, .name = "dot1qCustomerDEI", .data_type = .boolean },
    .{ .id = 390, .pen = null, .name = "flowSelectorAlgorithm", .data_type = .unsigned },
    .{ .id = 391, .pen = null, .name = "flowSelectedOctetDeltaCount", .data_type = .unsigned },
    .{ .id = 392, .pen = null, .name = "flowSelectedPacketDeltaCount", .data_type = .unsigned },
    .{ .id = 393, .pen = null, .name = "flowSelectedFlowDeltaCount", .data_type = .unsigned },
    .{ .id = 394, .pen = null, .name = "selectorIDTotalFlowsObserved", .data_type = .unsigned },
    .{ .id = 395, .pen = null, .name = "selectorIDTotalFlowsSelected", .data_type = .unsigned },
    .{ .id = 396, .pen = null, .name = "samplingFlowInterval", .data_type = .unsigned },
    .{ .id = 397, .pen = null, .name = "samplingFlowSpacing", .data_type = .unsigned },
    .{ .id = 398, .pen = null, .name = "flowSamplingTimeInterval", .data_type = .unsigned },
    .{ .id = 399, .pen = null, .name = "flowSamplingTimeSpacing", .data_type = .unsigned },
    .{ .id = 400, .pen = null, .name = "hashFlowDomain", .data_type = .unsigned },
    .{ .id = 401, .pen = null, .name = "transportOctetDeltaCount", .data_type = .unsigned },
    .{ .id = 402, .pen = null, .name = "transportPacketDeltaCount", .data_type = .unsigned },
    .{ .id = 403, .pen = null, .name = "originalExporterIPv4Address", .data_type = .ipv4_address },
    .{ .id = 404, .pen = null, .name = "originalExporterIPv6Address", .data_type = .ipv6_address },
    .{ .id = 405, .pen = null, .name = "originalObservationDomainId", .data_type = .unsigned },
    .{ .id = 406, .pen = null, .name = "intermediateProcessId", .data_type = .unsigned },
    .{ .id = 407, .pen = null, .name = "ignoredDataRecordTotalCount", .data_type = .unsigned },
    .{ .id = 408, .pen = null, .name = "dataLinkFrameType", .data_type = .unsigned },
    .{ .id = 409, .pen = null, .name = "sectionOffset", .data_type = .unsigned },
    .{ .id = 410, .pen = null, .name = "sectionExportedOctets", .data_type = .unsigned },
    .{ .id = 411, .pen = null, .name = "dot1qServiceInstanceTag", .data_type = .octet_array },
    .{ .id = 412, .pen = null, .name = "dot1qServiceInstanceId", .data_type = .unsigned },
    .{ .id = 413, .pen = null, .name = "dot1qServiceInstancePriority", .data_type = .unsigned },
    .{ .id = 414, .pen = null, .name = "dot1qCustomerSourceMacAddress", .data_type = .mac_address },
    .{ .id = 415, .pen = null, .name = "dot1qCustomerDestinationMacAddress", .data_type = .mac_address },
    .{ .id = 417, .pen = null, .name = "postLayer2OctetDeltaCount", .data_type = .unsigned },
    .{ .id = 418, .pen = null, .name = "postMCastLayer2OctetDeltaCount", .data_type = .unsigned },
    .{ .id = 420, .pen = null, .name = "postLayer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 421, .pen = null, .name = "postMCastLayer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 422, .pen = null, .name = "minimumLayer2TotalLength", .data_type = .unsigned },
    .{ .id = 423, .pen = null, .name = "maximumLayer2TotalLength", .data_type = .unsigned },
    .{ .id = 424, .pen = null, .name = "droppedLayer2OctetDeltaCount", .data_type = .unsigned },
    .{ .id = 425, .pen = null, .name = "droppedLayer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 426, .pen = null, .name = "ignoredLayer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 427, .pen = null, .name = "notSentLayer2OctetTotalCount", .data_type = .unsigned },
    .{ .id = 428, .pen = null, .name = "layer2OctetDeltaSumOfSquares", .data_type = .unsigned },
    .{ .id = 429, .pen = null, .name = "layer2OctetTotalSumOfSquares", .data_type = .unsigned },
    .{ .id = 430, .pen = null, .name = "layer2FrameDeltaCount", .data_type = .unsigned },
    .{ .id = 431, .pen = null, .name = "layer2FrameTotalCount", .data_type = .unsigned },
    .{ .id = 432, .pen = null, .name = "pseudoWireDestinationIPv4Address", .data_type = .ipv4_address },
    .{ .id = 433, .pen = null, .name = "ignoredLayer2FrameTotalCount", .data_type = .unsigned },
    .{ .id = 434, .pen = null, .name = "mibObjectValueInteger", .data_type = .signed },
    .{ .id = 435, .pen = null, .name = "mibObjectValueOctetString", .data_type = .octet_array },
    .{ .id = 436, .pen = null, .name = "mibObjectValueOID", .data_type = .octet_array },
    .{ .id = 437, .pen = null, .name = "mibObjectValueBits", .data_type = .octet_array },
    .{ .id = 438, .pen = null, .name = "mibObjectValueIPAddress", .data_type = .ipv4_address },
    .{ .id = 439, .pen = null, .name = "mibObjectValueCounter", .data_type = .unsigned },
    .{ .id = 440, .pen = null, .name = "mibObjectValueGauge", .data_type = .unsigned },
    .{ .id = 441, .pen = null, .name = "mibObjectValueTimeTicks", .data_type = .unsigned },
    .{ .id = 442, .pen = null, .name = "mibObjectValueUnsigned", .data_type = .unsigned },
    .{ .id = 443, .pen = null, .name = "mibObjectValueTable", .data_type = .sub_template_list },
    .{ .id = 444, .pen = null, .name = "mibObjectValueRow", .data_type = .sub_template_list },
    .{ .id = 445, .pen = null, .name = "mibObjectIdentifier", .data_type = .octet_array },
    .{ .id = 446, .pen = null, .name = "mibSubIdentifier", .data_type = .unsigned },
    .{ .id = 447, .pen = null, .name = "mibIndexIndicator", .data_type = .unsigned },
    .{ .id = 448, .pen = null, .name = "mibCaptureTimeSemantics", .data_type = .unsigned },
    .{ .id = 449, .pen = null, .name = "mibContextEngineID", .data_type = .octet_array },
    .{ .id = 450, .pen = null, .name = "mibContextName", .data_type = .string },
    .{ .id = 451, .pen = null, .name = "mibObjectName", .data_type = .string },
    .{ .id = 452, .pen = null, .name = "mibObjectDescription", .data_type = .string },
    .{ .id = 453, .pen = null, .name = "mibObjectSyntax", .data_type = .string },
    .{ .id = 454, .pen = null, .name = "mibModuleName", .data_type = .string },
    .{ .id = 455, .pen = null, .name = "mobileIMSI", .data_type = .string },
    .{ .id = 456, .pen = null, .name = "mobileMSISDN", .data_type = .string },
    .{ .id = 457, .pen = null, .name = "httpStatusCode", .data_type = .unsigned },
    .{ .id = 458, .pen = null, .name = "sourceTransportPortsLimit", .data_type = .unsigned },
    .{ .id = 459, .pen = null, .name = "httpRequestMethod", .data_type = .string },
    .{ .id = 460, .pen = null, .name = "httpRequestHost", .data_type = .string },
    .{ .id = 461, .pen = null, .name = "httpRequestTarget", .data_type = .string },
    .{ .id = 462, .pen = null, .name = "httpMessageVersion", .data_type = .string },
    .{ .id = 463, .pen = null, .name = "natInstanceID", .data_type = .unsigned },
    .{ .id = 464, .pen = null, .name = "internalAddressRealm", .data_type = .octet_array },
    .{ .id = 465, .pen = null, .name = "externalAddressRealm", .data_type = .octet_array },
    .{ .id = 466, .pen = null, .name = "natQuotaExceededEvent", .data_type = .unsigned },
    .{ .id = 467, .pen = null, .name = "natThresholdEvent", .data_type = .unsigned },
    .{ .id = 468, .pen = null, .name = "httpUserAgent", .data_type = .string },
    .{ .id = 469, .pen = null, .name = "httpContentType", .data_type = .string },
    .{ .id = 470, .pen = null, .name = "httpReasonPhrase", .data_type = .string },
    .{ .id = 471, .pen = null, .name = "maxSessionEntries", .data_type = .unsigned },
    .{ .id = 472, .pen = null, .name = "maxBIBEntries", .data_type = .unsigned },
    .{ .id = 473, .pen = null, .name = "maxEntriesPerUser", .data_type = .unsigned },
    .{ .id = 474, .pen = null, .name = "maxSubscribers", .data_type = .unsigned },
    .{ .id = 475, .pen = null, .name = "maxFragmentsPendingReassembly", .data_type = .unsigned },
    .{ .id = 476, .pen = null, .name = "addressPoolHighThreshold", .data_type = .unsigned },
    .{ .id = 477, .pen = null, .name = "addressPoolLowThreshold", .data_type = .unsigned },
    .{ .id = 478, .pen = null, .name = "addressPortMappingHighThreshold", .data_type = .unsigned },
    .{ .id = 479, .pen = null, .name = "addressPortMappingLowThreshold", .data_type = .unsigned },
    .{ .id = 480, .pen = null, .name = "addressPortMappingPerUserHighThreshold", .data_type = .unsigned },
    .{ .id = 481, .pen = null, .name = "globalAddressMappingHighThreshold", .data_type = .unsigned },
    .{ .id = 482, .pen = null, .name = "vpnIdentifier", .data_type = .octet_array },
    .{ .id = 483, .pen = null, .name = "bgpCommunity", .data_type = .unsigned },
    .{ .id = 484, .pen = null, .name = "bgpSourceCommunityList", .data_type = .basic_list },
    .{ .id = 485, .pen = null, .name = "bgpDestinationCommunityList", .data_type = .basic_list },
    .{ .id = 486, .pen = null, .name = "bgpExtendedCommunity", .data_type = .octet_array },
    .{ .id = 487, .pen = null, .name = "bgpSourceExtendedCommunityList", .data_type = .basic_list },
    .{ .id = 488, .pen = null, .name = "bgpDestinationExtendedCommunityList", .data_type = .basic_list },
    .{ .id = 489, .pen = null, .name = "bgpLargeCommunity", .data_type = .octet_array },
    .{ .id = 490, .pen = null, .name = "bgpSourceLargeCommunityList", .data_type = .basic_list },
    .{ .id = 491, .pen = null, .name = "bgpDestinationLargeCommunityList", .data_type = .basic_list },
    .{ .id = 492, .pen = null, .name = "srhFlagsIPv6", .data_type = .unsigned },
    .{ .id = 493, .pen = null, .name = "srhTagIPv6", .data_type = .unsigned },
    .{ .id = 494, .pen = null, .name = "srhSegmentIPv6", .data_type = .ipv6_address },
    .{ .id = 495, .pen = null, .name = "srhActiveSegmentIPv6", .data_type = .ipv6_address },
    .{ .id = 496, .pen = null, .name = "srhSegmentIPv6BasicList", .data_type = .basic_list },
    .{ .id = 497, .pen = null, .name = "srhSegmentIPv6ListSection", .data_type = .octet_array },
    .{ .id = 498, .pen = null, .name = "srhSegmentsIPv6Left", .data_type = .unsigned },
    .{ .id = 499, .pen = null, .name = "srhIPv6Section", .data_type = .octet_array },
    .{ .id = 500, .pen = null, .name = "srhIPv6ActiveSegmentType", .data_type = .unsigned },
    .{ .id = 501, .pen = null, .name = "srhSegmentIPv6LocatorLength", .data_type = .unsigned },
    .{ .id = 502, .pen = null, .name = "srhSegmentIPv6EndpointBehavior", .data_type = .unsigned },
    .{ .id = 503, .pen = null, .name = "transportChecksum", .data_type = .unsigned },
    .{ .id = 504, .pen = null, .name = "icmpHeaderPacketSection", .data_type = .octet_array },
    .{ .id = 505, .pen = null, .name = "gtpuFlags", .data_type = .unsigned },
    .{ .id = 506, .pen = null, .name = "gtpuMsgType", .data_type = .unsigned },
    .{ .id = 507, .pen = null, .name = "gtpuTEid", .data_type = .unsigned },
    .{ .id = 508, .pen = null, .name = "gtpuSequenceNum", .data_type = .unsigned },
    .{ .id = 509, .pen = null, .name = "gtpuQFI", .data_type = .unsigned },
    .{ .id = 510, .pen = null, .name = "gtpuPduType", .data_type = .unsigned },
    .{ .id = 511, .pen = null, .name = "bgpSourceAsPathList", .data_type = .basic_list },
    .{ .id = 512, .pen = null, .name = "bgpDestinationAsPathList", .data_type = .basic_list },
    .{ .id = 513, .pen = null, .name = "ipv6ExtensionHeaderType", .data_type = .unsigned },
    .{ .id = 514, .pen = null, .name = "ipv6ExtensionHeaderCount", .data_type = .unsigned },
    .{ .id = 515, .pen = null, .name = "ipv6ExtensionHeadersFull", .data_type = .unsigned },
    .{ .id = 516, .pen = null, .name = "ipv6ExtensionHeaderTypeCountList", .data_type = .sub_template_list },
    .{ .id = 517, .pen = null, .name = "ipv6ExtensionHeadersLimit", .data_type = .boolean },
    .{ .id = 518, .pen = null, .name = "ipv6ExtensionHeadersChainLength", .data_type = .unsigned },
    .{ .id = 519, .pen = null, .name = "ipv6ExtensionHeaderChainLengthList", .data_type = .sub_template_list },
    .{ .id = 520, .pen = null, .name = "tcpOptionsFull", .data_type = .unsigned },
    .{ .id = 521, .pen = null, .name = "tcpSharedOptionExID16", .data_type = .unsigned },
    .{ .id = 522, .pen = null, .name = "tcpSharedOptionExID32", .data_type = .unsigned },
    .{ .id = 523, .pen = null, .name = "tcpSharedOptionExID16List", .data_type = .basic_list },
    .{ .id = 524, .pen = null, .name = "tcpSharedOptionExID32List", .data_type = .basic_list },
    .{ .id = 525, .pen = null, .name = "udpSafeOptions", .data_type = .unsigned },
    .{ .id = 526, .pen = null, .name = "udpUnsafeOptions", .data_type = .unsigned },
    .{ .id = 527, .pen = null, .name = "udpExID", .data_type = .unsigned },
    .{ .id = 528, .pen = null, .name = "udpSafeExIDList", .data_type = .basic_list },
    .{ .id = 529, .pen = null, .name = "udpUnsafeExIDList", .data_type = .basic_list },
};

fn fieldKey(pen: u32, id: u16) u64 {
    return (@as(u64, pen) << 16) | id;
}

const FieldMap = std.AutoHashMap(u64, FieldInfo);

pub const Registry = struct {
    fields: FieldMap,

    pub fn init(allocator: Allocator) Allocator.Error!Registry {
        var fields = FieldMap.init(allocator);

        try fields.ensureTotalCapacity(iana.len);
        for (iana) |entry| {
            fields.putAssumeCapacity(fieldKey(0, entry.id), entry);
        }

        return .{ .fields = fields };
    }

    pub fn deinit(self: *Registry) void {
        self.fields.deinit();
    }

    pub fn put(self: *Registry, field: FieldInfo) Allocator.Error!void {
        const key = fieldKey(field.pen orelse 0, field.id);
        try self.fields.put(key, field);
    }

    pub fn lookup(self: *const Registry, id: u16, pen: ?u32) ?*const FieldInfo {
        const key = fieldKey(pen orelse 0, id);
        return self.fields.getPtr(key);
    }
};

const testing = std.testing;

test "lookup known IANA fields" {
    var reg = try Registry.init(testing.allocator);
    defer reg.deinit();

    const octet_delta = reg.lookup(1, null).?;
    try testing.expectEqualStrings("octetDeltaCount", octet_delta.name);
    try testing.expectEqual(.unsigned, octet_delta.data_type);

    const src_addr = reg.lookup(8, null).?;
    try testing.expectEqualStrings("sourceIPv4Address", src_addr.name);
    try testing.expectEqual(.ipv4_address, src_addr.data_type);

    const src_v6 = reg.lookup(27, 0).?;
    try testing.expectEqualStrings("sourceIPv6Address", src_v6.name);
    try testing.expectEqual(.ipv6_address, src_v6.data_type);
}

test "lookup unknown fields returns null" {
    var reg = try Registry.init(testing.allocator);
    defer reg.deinit();

    try testing.expectEqual(null, reg.lookup(0, null));
    try testing.expectEqual(null, reg.lookup(9999, null));
    try testing.expectEqual(null, reg.lookup(1, 12345));
}

test "add custom PEN field" {
    var reg = try Registry.init(testing.allocator);
    defer reg.deinit();

    try reg.put(.{ .id = 1, .pen = 9999, .name = "customField", .data_type = .string });

    const custom = reg.lookup(1, 9999).?;
    try testing.expectEqualStrings("customField", custom.name);
    try testing.expectEqual(.string, custom.data_type);

    // IANA field with same ID still works
    const iana_field = reg.lookup(1, null).?;
    try testing.expectEqualStrings("octetDeltaCount", iana_field.name);
}

test "override IANA field" {
    var reg = try Registry.init(testing.allocator);
    defer reg.deinit();

    try reg.put(.{ .id = 1, .pen = null, .name = "myOctetCount", .data_type = .unsigned });

    const overridden = reg.lookup(1, null).?;
    try testing.expectEqualStrings("myOctetCount", overridden.name);
}
